
//TRANSACTION REDUCER ACTIONS
export const TEST = 'TEST';
export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const DELETE_ALL_TRANSACTIONS = 'DELETE_ALL_TRANSACTIONS';
export const DELETE_ONE_TRANSACTION = 'DELETE_ONE_TRANSACTION';
export const DELETE_ALL_BILLS_FROM_TRANSACTIONS = 'DELETE_ALL_BILLS_FROMTRANSACTIONS';
export const POST_TRANSACTIONS = 'POST_TRANSACTIONS';

//FEEDBACK REDUCER ACTIONS
export const UPDATE_MESSAGE_BOARD = 'UPDATE_MESSAGE_BOARD';

//BILL REDUCER ACTIONS
export const GET_ALL_BILLS = 'GET_ALL_BILLS';
export const DELETE_ALL_BILLS = 'DELETE_ALL_BILLS';
export const DELETE_ONE_BILL = 'DELETE_ONE_BILL';
export const DELETE_BILL_REOCCURANCES = 'DELETE_BILL_REOCCURANCES';
export const POST_BILL = 'POST_BILL';

