
//TRANSACTION REDUCER ACTIONS
export const TEST = 'TEST';
export const GET_ALL_TRANSACTIONS = 'GET_ALL_TRANSACTIONS';
export const DELETE_ALL_TRANSACTIONS = 'DELETE_ALL_TRANSACTIONS';
export const POST_TRANSACTION = 'POST_TRANSACTION';

// FEEDBACK REDUCER ACTIONS
export const UPDATE_MESSAGE_BOARD = 'UPDATE_MESSAGE_BOARD';
